---
- hosts: localhost
  tasks:
    - name: Install needed pip depencies
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      loop:
        - { name: 'azure', version: '3.0.0' }
        - { name: 'ansible[azure]', version: '2.5.3' }
      become: True

    - name: Create folders
      file:
        state: directory
        recurse: yes
        path: "{{ playbook_dir }}/inventory"

    - name: Download azure inventory modules
      get_url:
        url: "https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/{{ item }}"
        dest: "{{ playbook_dir }}/inventory/{{ item }}"
      loop:
        - azure_rm.py
        - azure_rm.ini
    
    - name: Set excutable on azure_rm.py
      file:
        dest: "{{ playbook_dir }}/inventory/azure_rm.py"
        mode: "+x"

    - name: Create group vars folder
      file:
        state: directory
        recurse: yes
        path: "{{ playbook_dir }}/inventory/group_vars"
    
    - name: Create required Group_vars
      set_fact:
        ansible_user: edeneuve
        
    - name: Test if inventory is ok
      command:  python {{ playbook_dir }}/inventory/azure_rm.py
      register: test
    
